### ISSUE TITLE
First Runthrough Feedback

### ISSUE THREAD

**Issue by tkellen** [Zipcar/vault-cfcs#2]
Simple contributing / developer workflow. Nice!

My machine:
```
➜ uname -a
Linux devbox 4.18.12-arch1-1-ARCH #1 SMP PREEMPT Thu Oct 4 01:01:27 UTC 2018 x86_64 GNU/Linux
```
```
➜ go version
go version go1.11.1 linux/amd64
```
```
➜ make --version
GNU Make 4.2.1
```
```
➜ vboxmanage --version
5.2.18r123745
```

Worked as expected:
```
make
make test
make build
make run
make fmt
```

Failed:
```
make bosh-lite
```

**Problem:** No `bin` directory, the `bin/blite` target failed. 
**Workaround:** `mkdir bin`

**Problem:** Subsequent run failed because `tasks/bootstrap-local-director` assumed `./bin` was in my path. 
**Workaround:** `export PATH=$PATH:./bin`.

**Problem:**  Subsequent run failed because `bin/blite` was missing execute bit.
**Workaround:**  `chmod +x bin/blite`.

**Problem:** Subsequent run failed because I did not have bosh-cli installed.
**Workaround:**  `curl -SsLo bin/bosh https://github.com/cloudfoundry/bosh-cli/releases/download/v5.3.1/bosh-cli-5.3.1-linux-amd64 && chmod +x bin/bosh`. 

**Problem:** Saw a pile of output that all appears to work correctly. Success?!
**Suggestion:** Include commands that show how to wire everything together and validate the thing works once blite does its thing.

**Comment by MattSurabian** [comment]
Thank you, sir for your thorough and much appreciated feedback! Making these changes today

**Comment by MattSurabian** [comment]
Landed in master https://github.com/Zipcar/vault-cfcs/commit/cbff570c362fbae3f116279384c2d7b1b0cb705b
